arch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = "quiz"

urlpatterns = [
    path("", views.MainPage.as_view(), name="index"),
    path("quiz/", views.MainPage.as_view(), name="quiz_list"),
    path("quiz/<str:group_slug>/", views.test_groups, name="test_groups"),

    path("questions/<int:question_id>/grade/", views.grade_question, name="grade_question"),
]

quiz/models.py
import typing

from django.contrib.postgres import fields
from django.db import models


class TestGroup(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(default='')

    objects = models.Manager()

    def __str__(self):
        return self.name


class Quiz(models.Model):
    name = models.CharField(max_length=100)
    test_group = models.ForeignKey(TestGroup, on_delete=models.DO_NOTHING, null=True)

    objects = models.Manager()

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    prompt = models.CharField(max_length=200)

    objects = models.Manager()

    def __str__(self):
        return self.prompt

    def get_answer(self) -> typing.Union["Answer", None]:
        return getattr(self, "multiplechoiceanswer", None) or getattr(self, "freetextanswer", None)


class Answer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    correct_answer = models.CharField(max_length=200)

    objects = models.Manager()

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.correct_answer

    def is_correct(self, user_answer) -> bool:
        return user_answer == self.correct_answer


class FreeTextAnswer(Answer):
    case_sensitive = models.BooleanField(default=False)

    objects = models.Manager()

    def is_correct(self, user_answer) -> bool:
        if not self.case_sensitive:
            return user_answer.lower() == self.correct_answer.lower()
        return user_answer == self.correct_answer


class MultipleChoiceAnswer(Answer):
    choices = fields.ArrayField(models.CharField(max_length=200, blank=True))

    objects = models.Manager()

    def __str__(self) -> str:
        return f"{self.correct_answer} from {self.choices}"

quiz/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic, View
from django.http.request import HttpRequest

from .models import Question, Quiz, TestGroup


class IndexView(generic.ListView):
    model = Quiz
    template_name = "quiz/index.html"


class MainPage(View):
    def get(self, request: HttpRequest):
        group_list = TestGroup.objects.all()
        return render(
            request,
            "quiz/index.html",
            {"group_list": group_list},
        )


def display_quiz(request: HttpRequest, quiz_id: int):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = quiz.question_set.first()
    return redirect(reverse("quiz:display_question", kwargs={"quiz_id": quiz_id, "question_id": question.pk}))


def test_groups(request: HttpRequest, group_slug):
    group = get_object_or_404(TestGroup, slug=group_slug)
    quiz_list = Quiz.objects.filter(test_group=group)

    question_id = request.GET.get('question')

    if question_id is None:
        return render(
            request,
            "quiz/quiz_list.html",
            {"quiz_list": quiz_list, "group_name": group.name},
        )
    else:
        current_question = get_object_or_404(Question, pk=question_id)
        quiz = get_object_or_404(Quiz, pk=current_question.quiz.id)
        questions = quiz.question_set.all()

        next_question = None

        for index, question in enumerate(questions):
            if question.id == int(question_id):
                if index != len(questions) - 1:
                    next_question = questions[index + 1]

        return render(
            request,
            "quiz/display.html",
            {"quiz": current_question.quiz, "question": current_question, "next_question": next_question},
        )


def display_question(request: HttpRequest, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = quiz.question_set.all()
    current_question, next_question = None, None
    for ind, question in enumerate(questions):
        if question.pk == question_id:
            current_question = question
            if ind != len(questions) - 1:
                next_question = questions[ind + 1]

    return render(
        request,
        "quiz/display.html",
        {"quiz": quiz, "question": current_question, "next_question": next_question},
    )


def grade_question(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answer = question.get_answer()

    if answer is None:
        return render(request, "quiz/partial.html", {"error": "Question must have an answer"}, status=422)

    is_correct = answer.is_correct(request.POST.get("answer"))

    return render(
        request,
        "quiz/partial.html",
    )

quiz/templates/quiz/base.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Тесты</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
<nav class="py-2 bg-body-tertiary border-bottom">
<div class="container d-flex flex-wrap">
  <ul class="nav me-auto">
    <li class="nav-item"><a href="/" class="nav-link link-dark px-2 active" aria-current="page">Главная</a></li>
  </ul>
  <ul class="nav">
    <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Вход</a></li>
    <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Регистрация</a></li>
  </ul>
</div>
</nav>

{% block page_content %}{% endblock %}
</body>
</html>

quiz/templates/quiz/display.html
{% extends 'quiz/base.html' %}

{% block page_content %}
<div class="container">
<h1>Quiz: {{ quiz.name }}</h1>

<section class="question">
{% if question %}
<form id="question-form" action="{% url 'quiz:grade_question' question.id %}" method="post">
    {% csrf_token %}

    <fieldset class="form-group">
        <legend>{{ question.prompt }}</legend>
        {% for choice in question.multiplechoiceanswer.choices %}
        <div class="radio">
        <label>
            <input type="radio" class="answer-radio" name="answer" value="{{ choice }}">
            {{ choice}}
        </label>
        </div>
        {% endfor %}
    </fieldset>
    <button type="submit" id="submit-btn" class="btn btn-primary d-none">Отправить ответ</button>
</form>

<div id="question-feedback" style="margin-top:16px">
</div>
{% else %}
Sorry, that question doesn't exist in this quiz.
{% endif %}
</section>

{% if next_question %}
<div style="margin-top:12px; font-size:16px" class="d-none" id="next-question">
<a href="{% url 'quiz:test_groups' quiz.test_group.slug %}?question={{ next_question.id }}">Следующий вопрос →</a>
</div>
{% endif %}
</div>

<script>

document.addEventListener("DOMContentLoaded", () => {
    const answerRadioList = document.querySelectorAll('.answer-radio')
    answerRadioList.forEach(radio => {
        radio.addEventListener('change', event => {
            const submitBtn = document.getElementById('submit-btn')
            submitBtn.classList.remove('d-none')
        })
    })
})

const form = document.getElementById("question-form");
form.addEventListener("submit", (e) => {
    e.preventDefault();
    document.getElementById('submit-btn').disabled = true
    fetchAnswer(form)
});

async function fetchAnswer(form) {
    const response = await fetch(form.action, {method:'post', body: new FormData(form)});
    if (response.status === 200) {

        document.getElementById("question-feedback").innerHTML = await response.text();
        const nextQuestion = document.getElementById("next-question");

        if (nextQuestion) {
            nextQuestion.classList.remove('d-none')
        }
    } else {
        document.getElementById("question-feedback").innerHTML = await response.text();
    }
}

</script>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}

{% block page_content %}

<div class="container">
    <h1>Группы тестов</h1>
{% if group_list %}
<ul>
{% for group in group_list %}
    <li><a href="{% url 'quiz:test_groups' group.slug %}">{{ group.name }}</a></li>
{% endfor %}
</ul>
{% else %}
    <p>Группы не созданы</p>
{% endif %}
</div>

{% endblock %}

quiz/templates/quiz/partial.html
{% if error %}
<div class="alert alert-danger" role="alert">
  {{ error }}
</div>
{% else %}

✅ ответ принят!

{% endif %}

quiz/templates/quiz/quiz_list.html
{% extends 'quiz/base.html' %}

{% block page_content %}

<div class="container">
    <h1>Список тестов: {{ group_name }}</h1>
{% if quiz_list %}
<ul>
{% for quiz in quiz_list %}
    <li><a href="{% url 'quiz:test_groups' quiz.test_group.slug %}?question={{ quiz.id }}">{{ quiz.name }}</a></li>
{% endfor %}
</ul>
{% else %}
    <p>Тесты не созданы</p>
{% endif %}
</div>

{% endblock %}